openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  termsOfService: http://swagger.io/terms/
  contact:
    email: apiteam@swagger.io
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8080/api/
tags:
  - name: flight
    description: Information about flights
  - name: pet
    description: Everything about your Pets
    externalDocs:
      description: Find out more
      url: http://swagger.io
  - name: store
    description: Access to Petstore orders
    externalDocs:
      description: Find out more about our store
      url: http://swagger.io
  - name: user
    description: operations regarding authentication
paths:
  /allflights:
    get:
      tags:
        - flight
      summary: Search flights
      description: Search flights by different criteria
      parameters:
        - name: from
          in: query
          description: departure airport IATA
          required: false
          explode: true
          schema:
            type: string
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/allflights'          
        '404':
          description: No flight matched the query
components:
  schemas:
    allflights:
      type: object
      properties:
        id: 
          type: object
          properties:
            timestamp:
              type: integer
            date:
              type: string
        flightNumber:
          type: string
        flightIata:
          type: string
        departure:
          $ref: '#/components/schemas/airportFlight'
        arrival:
          $ref: '#/components/schemas/airportFlight'
            
    airportFlight:
      type: object
      properties:
        iata:
          type: string
        icao:
          type: string
        name:
          type: string
        terminal:
          type: string
        gate:
          type: string
        delay:
          type: int
        scheduled:
          type: string
        estimated:
          type: string
        actual:
          type: string